### ISSUE TITLE
Support other testtypes

### ISSUE THREAD

**Issue by kkoehn** [openHPI/proforma#117]
- [ ] regex
- [ ] unittest
- [ ] checkstyle

Also validate those in the buildprocess

- [x] somehow map schema namespace to file(name)
- [ ] try to validate any_node in `import_helpers.rb:69`
  - according to [1] I should be able to validate a slightly modified version of the unittest (have to get the node, export it with `to_xml(save_with: 0)` to a string without needless newlines, then parse it again and get a nokogiri:document. Then I have to add the `unit` namespace to the unittest node. (see picture [2]). Nokogiri doesn't agree yet, that this is valid though.

[1]: https://extendsclass.com/xml-schema-validator.html
2:
![Screenshot_20230208_230057](https://user-images.githubusercontent.com/24592181/217661747-4cc57d01-42f7-4beb-b84a-51569dfd34e5.png)

Breakpoint in `import_helpers.rb:69`
```
fdoc = Nokogiri::XML(configuration_any_node.to_xml(save_with: 0)
fdoc.children.first.add_namespace_definition('unit', 'urn:proforma:tests:unittest:v1.1')

schema = Nokogiri::XML::Schema(File.read(Proforma::SCHEMA_FORMAT_PATH % 'unittest'))
schema.validate fdoc
```

- [ ] Save xml as json 
```
{
  unittest: 
    {
      attributes: [{key: value}, "check if onlykey?? is possible"], 
      children:[{another_node, "string"}]
    }
}
```

- [ ] check all ##other nodes for proforma namespaces and schemas

**Comment by kkoehn** [comment]
Trying to use the new Dachsfisch gem to convert arbitrary XML-Nodes to JSON creates new problems:
- In case of testtypes, the namespace is not registered at the root of the node but at the root of the document:
``` XML
<unit:unittest framework="JUnit" version="4.10">
  <unit:entry-point>HelloWorldTest</unit:entry-point>
</unit:unittest>
```
Nokogiri notices the missing namespace and Dachsfisch reraises it (`xml2_json_converter.rb:9`)
If we disable the reraise and ignore the error, we could use Dachsfisch to get the following json:
```JSON
{
  "unit:unittest":{
    "unit:entry-point": {
      "$1":"HelloWorldTest"
    },
    "@framework":"JUnit","@version":"4.10"
  }
}
```
- another option would be to create a new document from the snippet and manually add the used namespace(s). This would result in 
``` JSON
{
    "unittest": {
        "@framework": "JUnit",
        "@version": "4.10",
        "@xmlns": {
            "unit": "urn:proforma:tests:unittest:v1.1"
        },
        "unit:entry-point": {
            "$1": "HelloWorldTest",
            "@xmlns": {
                "unit": "urn:proforma:tests:unittest:v1.1"
            }
        }
    }
}
```
This feels like the desired output, but getting there is inconvenient. We may think about adding an option to Dachsfisch to either supply namespaces or Nokogiri-Nodes as input.

**Comment by kkoehn** [comment]
Correction regarding the second JSON snippet:
The root node (line 2) does not have a namespace prefix. This is a bug in dachfisch

**Comment by MrSerth** [comment]
Ah, thanks for fixing the issue. I just reviewed and merged your PR openhpi/dachsfisch#25, resolving the issue you mentioned. This "just" leaves us back with the original problem. 

My actual intuition would have been the last solution you suggested: Manually passing the respective namespace to the converter. For this, I would also think that extending dachsfisch to support custom namespace passing might be a good idea.

**Comment by kkoehn** [comment]
The converters can extract the namespace from the input xml/json. My problem was that I had to add it to the existing document (builder), but I found a way.

**Comment by MrSerth** [comment]
Alright, great. Regarding the regex test: Do you think we should include our slightly modified XSD in the gem? I remember that we had a discussion about a bug in the official XSD (and a solution to that), but cannot find the discussion. As far as I remember, the change we considered wasn't too much, but required in order to make regex definitions work as expected, right?

**Comment by kkoehn** [comment]
I found your suggested change:

```
Subject: [PATCH] Fix RegExp Test to allow actual RegEx
---
Index: assets/schemas/proforma-regexptest.xsd
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/assets/schemas/proforma-regexptest.xsd b/assets/schemas/proforma-regexptest.xsd
--- a/assets/schemas/proforma-regexptest.xsd    (revision 3fc893bf5342b98462623b8577a1eafdaae64f92)
+++ b/assets/schemas/proforma-regexptest.xsd    (date 1676675997545)
@@ -34,7 +34,11 @@
     </xs:element>
 
     <xs:complexType name="regexpType">
-        <xs:attributeGroup ref="ns1:regexp-flags"/>
+        <xs:simpleContent>
+            <xs:extension base="xs:string">
+                <xs:attributeGroup ref="ns1:regexp-flags"/>
+            </xs:extension>
+        </xs:simpleContent>
     </xs:complexType>
     <!-- attributes to define, which regexp-flags are applied to a specified regular expression -->
     <xs:attributeGroup name="regexp-flags">
```

**Comment by MrSerth** [comment]
Indeed, right. If including the proforma-regexptest.xsd, I would go with this change (maybe in a separate commit, allowing us to identify the change later). I remember searching for changes in their XSD and concluding that this was a mistake introduced by migrating from ProFormA 1.x to 2.x. Sure, silently changing the XSD is not nice, but a) we are missing a working example as of now and b) the working group is no longer developing the schema further (in which case it's just us fixing the problem). Once we have it implemented, I can also reach out to them.
