### ISSUE TITLE
Support for ProFormA version 2.1

### ISSUE THREAD

**Issue by MrSerth** [openHPI/proforma#190]
We should add support for the newest [ProFormA version 2.1](https://github.com/ProFormA/proformaxml). It has been formally released in December 2020 and does not contain many changes except for a new "any" tag.

This version should be the default version and support for version 2.0.1 should be dropped (it was never released officially and we provide the only tool working with this version).

**Comment by kkoehn** [comment]
should we continue to support Proforma 2.0?

**Comment by MrSerth** [comment]
If I remember correctly, most tools I checked are already ProFormA 2.1 but some might be 2.0. At least for importing, I would argue that supporting both makes sense, but ideally we support both version. However, if some advanced features won't work with ProFormA 2.0 (like the custom annotations in the meta data), I wouldn't spend too much time on that but rather leave it for 2.1
